name: Build and Publish Blog

on: 
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
        run: |
          - git clone https://github.com/dianbanjiu/dianbanjiu.github.io public
      - name: build hugo
        run: hugo
      - name: deploy hugo
        run: |
          - cd public
          - git add .
          - git commit -m "ci post"
          - git push origin master